#!/usr/bin/env python3
#
# Copyright (c) 2025 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Generate validation/rules.ttl from the spec.json manifests.

The manifests stay the editable source: JSON is what a person adds a rule to,
and what the runner reads. This turns that same content into a graph, so the
catalog can be queried rather than only read -- "every rule of every
specification that builds on Part 3 and is still a gap" is a SPARQL query
against rules.ttl and a manual scan of four Markdown files otherwise.

Regenerate after editing any manifest:

    python3 validation/tools/make_rules_graph.py

Identifiers follow the URN scheme documented in validation/vocabulary.ttl. They
are derived here rather than stored in the manifests: an IRI written out by
hand in two places is an IRI that will disagree with itself eventually.
"""

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VALIDATION_DIR = HERE.parent
SPECS_DIR = VALIDATION_DIR / 'specs'
OUTPUT = VALIDATION_DIR / 'rules.ttl'

VOCAB = 'urn:opcua:validation:vocab:'


def spec_iri(document_number):
    return f'urn:opcua:validation:spec:{document_number}'


def rule_iri(document_number, rule_id):
    return f'urn:opcua:validation:rule:{document_number}:{rule_id}'


def escape(text):
    """Escape a Python string for a Turtle double-quoted literal."""
    return text.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


def load_manifests():
    manifests = []
    for path in sorted(SPECS_DIR.iterdir()):
        manifest_path = path / 'spec.json'
        if manifest_path.is_file():
            manifests.append(json.loads(manifest_path.read_text()))
    return manifests


def render(manifests):
    by_id = {manifest['id']: manifest for manifest in manifests}
    lines = [
        '@prefix opcv: <urn:opcua:validation:vocab:> .',
        '@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .',
        '',
        '# GENERATED by validation/tools/make_rules_graph.py -- do not edit.',
        '# Source of truth is the spec.json manifest of each specification.',
        '# Scheme and vocabulary: validation/vocabulary.ttl',
        '',
    ]

    for manifest in manifests:
        document = manifest['documentNumber']
        subject = f'<{spec_iri(document)}>'
        lines.append(f'{subject} a opcv:Specification ;')
        lines.append(f'    rdfs:label "{escape(manifest["title"])}" ;')
        lines.append(f'    opcv:documentNumber "{escape(document)}" ;')
        for dependency in manifest.get('dependsOn') or []:
            target = by_id.get(dependency)
            if target is None:
                # A dependency naming a spec that is not present is a manifest
                # error, not something to paper over with a dangling IRI.
                print(f'error: {manifest["id"]} dependsOn unknown spec {dependency}',
                      file=sys.stderr)
                return None
            lines.append(f'    opcv:buildsOn <{spec_iri(target["documentNumber"])}> ;')
        lines[-1] = lines[-1].rstrip(' ;') + ' .'
        lines.append('')

        for rule in manifest['rules']:
            rule_subject = f'<{rule_iri(document, rule["id"])}>'
            lines.append(f'{rule_subject} a opcv:ValidationRule ;')
            lines.append(f'    opcv:ruleId "{escape(rule["id"])}" ;')
            lines.append(f'    opcv:definedBy {subject} ;')
            if rule.get('section'):
                lines.append(f'    opcv:specSection "{escape(rule["section"])}" ;')
            if rule.get('summary'):
                lines.append(f'    rdfs:label "{escape(rule["summary"])}" ;')
            status = rule.get('status', 'implemented' if rule.get('shape') else 'gap')
            lines.append(f'    opcv:status "{escape(status)}" .')
            lines.append('')

    return '\n'.join(lines)


def main():
    manifests = load_manifests()
    if not manifests:
        print(f'No spec.json found under {SPECS_DIR}', file=sys.stderr)
        return 1

    turtle = render(manifests)
    if turtle is None:
        return 1

    OUTPUT.write_text(turtle)
    rules = sum(len(manifest['rules']) for manifest in manifests)
    print(f'{OUTPUT.relative_to(VALIDATION_DIR.parent)}: '
          f'{len(manifests)} specification(s), {rules} rule(s)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
